language: node_js
node_js:
  - 12.18.3
cache:
  directories:
   - node_modules
before_script:
 - npm run compile
env:
 - CXX=g++-4.8
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.8
